services:
  - type: web
    name: blog-website
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-website-db
          property: connectionString
      - key: JWT_KEY
        value: ryugaistheownerofL-DragoListenyoufoolishpersonwhy123areyoureading@thisprivatekeyy???
      - key: PORT
        value: "3000"
    plan: free
    region: singapore
    staticPublishPath: public

databases:
  - name: blog-website-db
    plan: free
    region: singapore
    postgresVersion: 14